=== jakob-ableitner1/university-app/src/main/resources/terms-list.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="TermType" >
        <xs:sequence>
            <xs:element name="termName" type="xs:string"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="endDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="TermsListType">
        <xs:sequence>
            <xs:element name="term" type="TermType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="termsList" type="TermsListType"/>
</xs:schema>

=== jakob-ableitner1/university-app/src/main/resources/terms-list.xml
<?xml version="1.0" encoding="UTF-8"?>

<termsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="terms-list.xsd">
    <term id="1">
        <termName>Spring 2024</termName>
        <startDate>2024-01-06</startDate>
        <endDate>2024-05-24</endDate>
    </term>
    <term id="2">
        <termName>Fall 2024</termName>
        <startDate>2024-08-06</startDate>
        <endDate>2024-12-24</endDate>
    </term>
</termsList>
