=== jakob-ableitner1/university-app/src/main/resources/datastorage/addresses.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="streetLine" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="state" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="zipCode" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="AddressesType">
        <xs:sequence>
            <xs:element name="address" type="AddressType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="addresses" type="AddressesType"/>
</xs:schema>

=== jakob-ableitner1/university-app/src/main/resources/addresses.xml
<?xml version="1.0" encoding="UTF-8"?>

<addresses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="addresses.xsd">
    <address id="1">
        <streetLine>40th street</streetLine>
        <city>St. Paul</city>
        <state>Minnesota</state>
        <country>USA</country>
        <zipCode>3456</zipCode>
    </address>
    <address id="2">
        <streetLine>60th street</streetLine>
        <city>Minneapolis</city>
        <state>Minnesota</state>
        <country>USA</country>
        <zipCode>321</zipCode>
    </address>
    <address id="3">
        <streetLine>80th street</streetLine>
        <city>St. Paul</city>
        <state>Minnesota</state>
        <country>USA</country>
        <zipCode>3456</zipCode>
    </address>
</addresses>
